server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: url-porxy-1
        uri: https://blog.csdn.net
        predicates:
        - Path=/baidu

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7979/eureka/

